### ISSUE TITLE
Support italic in JSX/TSX attribute names

### ISSUE THREAD

**Issue by deepu105** [idbartosz/vscode-darkpp-italic#1]
This is an awesome theme. It would be nice to have italics for the JSX/TSX attributes like below
![image](https://user-images.githubusercontent.com/1107223/35387362-b62c0b3e-01cf-11e8-811e-e1f3d8f8ea39.png)

**Comment by idbartosz** [comment]
Sorry for so long :sweat_smile: - I didn't get notification. Support for italic attribute names added.

**Comment by deepu105** [comment]
You are awesome, when will it be released.

**Comment by deepu105** [comment]
Nevermind, found the latest release. thanks

**Comment by idbartosz** [comment]
👍
