### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by VajraVaaltaa** [idbartosz/vscode-darkpp-italic#2]
Sorry, but could you explain in more detail how and where to prepend the code:

.mtki {
        font-size: 1.125em;
        font-stretch: ultra-condensed;
}

Thank you.

**Comment by idbartosz** [comment]
Sorry for so long. You've probably solve this issue already but for clarification:

**Windows 10:**
`C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.main.css`

![obraz](https://user-images.githubusercontent.com/21260478/49022285-c8232380-f194-11e8-993e-8fc54be8fd89.png)

![obraz](https://user-images.githubusercontent.com/21260478/49022636-99f21380-f195-11e8-8013-31d66e95b584.png)
