### ISSUE TITLE
Your Code installation appears to be corrupt. Please reinstall.

### ISSUE THREAD

**Issue by Maximebpro** [idbartosz/vscode-darkpp-italic#4]
Hello. thanks a lot for this extension. 

When I start vscode, i get the `Your Code installation appears to be corrupt. Please reinstall.` toaster message. I suppose it comes from my edition of `<path to VScode>\resources\app\out\vs\workbench.main.css`. 

Do you think we could have a "cleaner" way of getting this without "corrupting" vscode installation?

**Comment by idbartosz** [comment]
@Maximebpro 
I've pointed it in the `README.md`, you can disable this warning by clicking the gear icon in the warning message.

I'm not sure if VScode provides a less hacky way to change the style of all _italic_ fonts, if you know such way please make a PR so we can remove this hack. Anyways, change in `workbench.main.css` is purely cosmetics (and optional) to make "operator mono like" fonts look a bit better.
